# Generated by Django 3.2.5 on 2021-12-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=40)),
                ('category_name', models.CharField(max_length=40)),
                ('category_duration', models.DurationField()),
                ('category_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Booking Categories',
            },
        ),
        migrations.CreateModel(
            name='CurrentBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment', models.BooleanField()),
                ('has_paid', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Current Bookings',
            },
        ),
        migrations.CreateModel(
            name='Photographers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer_first_name', models.CharField(max_length=40)),
                ('photographer_last_name', models.CharField(max_length=40)),
                ('photographer_expertise', models.CharField(max_length=40)),
                ('photographer_experience', models.IntegerField()),
                ('photographer_pay', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Photographers',
                'ordering': ['photographer_last_name', 'photographer_first_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=30)),
                ('user_password', models.CharField(max_length=50)),
                ('user_account_name', models.CharField(max_length=30)),
                ('is_super_user', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'User',
                'ordering': ['-user_first_name'],
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment', models.BooleanField()),
                ('order_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
                ('user_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.currentbookings')),
            ],
            options={
                'verbose_name_plural': 'User History',
                'db_table': 'UserHistory',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_city', models.CharField(max_length=30)),
                ('user_district', models.CharField(max_length=30)),
                ('user_country', models.CharField(max_length=50)),
                ('user_zip_code', models.IntegerField()),
                ('user_street', models.CharField(max_length=30)),
                ('user_house_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
            options={
                'verbose_name_plural': 'User Address',
            },
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('begins_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.bookingcategories')),
            ],
            options={
                'verbose_name_plural': 'Service Details',
                'db_table': 'ServiceDetails',
            },
        ),
        migrations.AddField(
            model_name='currentbookings',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.servicedetails'),
        ),
        migrations.AddField(
            model_name='currentbookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
    ]
